Increment14
igorrnk/ypmetrika pull request #15
Opened 2023-02-21 15:15 UTC by igorrnk

2023-02-23 07:05 UTC, Barugoo commented on internal/agents/agent.go
> +	}
Кажется, что сделав воркерпул здесь нам ничего не мешает нафигачить запросов из другой части приложения. Я предлагаю сделать воркер-пул на уровне HTTP-клиента, чтобы все хттп-запросы которые делаются в агенте обязательно шли через него. Вот как идея:
https://codereview.stackexchange.com/questions/268404/golang-http-client-wrapper-with-rate-and-concurrency-limiting

2023-02-23 07:06 UTC, Barugoo commented on internal/agents/agent.go
> +		case models.GopsutilSource:
А нужен ли нам switch-case из двух кейсов? Не проще ли это сделать через if-else?

2023-02-23 07:09 UTC, Barugoo commented on internal/delivery/resty_client.go
> +	}
Мне кажется не очень правильно, то что у нас клиент принимает решение что делать с ошибками (т.е - логгировать) - пусть он лучше смотрит статус ответа, пробрасывает ошибки если что-то не так и уже вызывающий код пусть думает что с этими ошибками делать. Так мы сможем переиспользовать этот клиент в тех частях кода, где нам нужно не просто логгировать ошибку, а как-то ее обрабатывать

2023-02-23 07:11 UTC, Barugoo requested changes
Почему-то я вижу в PR-е изменения относящиеся к предыдущему спринту (работа с базой). Подлей пожалуйста ветки 3го спринта в мастер, а после этого мастер подлей в ветку 14го инкремента

Так же оставил комментарии

2023-03-01 13:10 UTC, igorrnk commented on internal/agents/agent.go
> +		case models.GopsutilSource:
+

2023-03-01 15:23 UTC, igorrnk commented on internal/agents/agent.go
> +	}
+

2023-03-01 15:24 UTC, igorrnk commented on internal/delivery/resty_client.go
> +	}
+

2023-03-02 13:12 UTC, igorrnk commented
Поправил.
Замечания тоже учел.

2023-03-02 13:13 UTC, igorrnk commented on internal/agents/agent.go
> +	}
Перенес в клиент.

2023-03-02 13:14 UTC, igorrnk commented on internal/agents/agent.go
> +		case models.GopsutilSource:
Сделал if.

2023-03-02 13:15 UTC, igorrnk commented on internal/delivery/resty_client.go
> +	}
Добавил в сигнатуру функций error

2023-03-04 15:26 UTC, merged